# Generated by Django 4.0.3 on 2022-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3999)),
                ('music', models.CharField(max_length=3999)),
            ],
        ),
    ]
