# Generated by Django 4.0.3 on 2022-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='music',
            field=models.CharField(max_length=19999999),
        ),
    ]
