# Generated by Django 4.0.3 on 2022-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_channel_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='copyrights',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
