# Generated by Django 4.0.3 on 2022-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_song_copyrights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
