# Generated by Django 4.0.3 on 2022-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_alter_song_copyrights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='copyrights',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
