# Generated by Django 4.0.3 on 2022-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
